services:


  realguard-api:

    build: .

    container_name: realguard-api

    ports:
      - "8000:8000"

    volumes:
      - ./ml/mlruns:/app/ml/mlruns
      - ./ml/mlflow.db:/app/ml/mlflow.db
    environment:
      MLFLOW_TRACKING_URI: sqlite:////app/ml/mlflow.db
    restart: unless-stopped


  mlflow-ui:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-ui
    ports:
      - "5000:5000"
    volumes:
      - ./ml/mlruns:/app/ml/mlruns
      - ./ml/mlflow.db:/app/ml/mlflow.db
    command: mlflow server --backend-store-uri sqlite:///app/ml/mlflow.db --default-artifact-root /app/ml/mlruns --host 0.0.0.0 --port 5000
    restart: unless-stopped

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:29093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Q'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - kafka
    restart: unless-stopped


